#!/usr/bin/env bash

# Set environment
export BSPWM_CONFIG="$HOME/.config/bspwm"

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Set default cursor
xsetroot -cursor_name left_ptr

# Set workspaces per monitor
for monitor in $(bspc query -M); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

# BSPWM Configuration
bspc config window_gap            10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# BSPWM coloring
bspc config normal_border_color   "#3B4252"
bspc config active_border_color   "#465780"
bspc config focused_border_color  "#FE6B70"
bspc config presel_feedback_color "#FE6B70"

# Window rules
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Gimp desktop='^4' follow=on focus=on
bspc rule -a vlc desktop='^5' follow=on focus=on
bspc rule -a Spotify desktop='^5' follow=on focus=on

# Autostart
# Set japan as default theme
"$BSPWM_CONFIG"/scripts/theme-switcher.sh japan &

# Start polybar
"$BSPWM_CONFIG"/rices/japan/polybar/launch.sh &

# Start picom
picom --config "$HOME"/.config/picom/picom.conf &

# Set wallpaper
feh --bg-fill "$BSPWM_CONFIG"/rices/japan/wallpapers/japan-wallpaper.jpg &

# Save default theme
echo "japan" > "$BSPWM_CONFIG"/current_theme
