#!/bin/bash

# BSPWM Configuration
bspc config border_width        3
bspc config window_gap         10
bspc config split_ratio        0.50

# Theme initialization script will be called here
$HOME/.config/bspwm/scripts/theme-switcher.sh japan
