#!/usr/bin/env bash
#  Sunset theme script
#  By diogofmonteiro

# Import Current Theme
source "$HOME"/.config/bspwm/themes/sunset/theme.sh

# Set bspwm configuration for Sunset
set_bspwm_config() {
    bspc config border_width "$bspwm_border"
    bspc config window_gap "$bspwm_gap"
    bspc config split_ratio "$bspwm_sratio"
}

# Reload terminal colors
set_term_config() {
    cat > "$HOME"/.config/alacritty/colors.yml << EOF
colors:
    primary:
        background: '${background}'
        foreground: '${foreground}'
    cursor:
        text: '${background}'
        cursor: '${cursor}'
    normal:
        black: '${color0}'
        red: '${color1}'
        green: '${color2}'
        yellow: '${color3}'
        blue: '${color4}'
        magenta: '${color5}'
        cyan: '${color6}'
        white: '${color7}'
    bright:
        black: '${color8}'
        red: '${color9}'
        green: '${color10}'
        yellow: '${color11}'
        blue: '${color12}'
        magenta: '${color13}'
        cyan: '${color14}'
        white: '${color15}'
EOF
}

# Set compositor configuration
set_picom_config() {
    sed -i "s/frame-opacity = .*/frame-opacity = $picom_opacity/g" "$HOME"/.config/picom.conf
}

main() {
    # Set bspwm configs
    set_bspwm_config
    
    # Set terminal colors
    set_term_config
    
    # Set compositor settings
    set_picom_config
    
    # Launch apps
    ./"$HOME"/.config/polybar/launch.sh
}
